"""
Disclaimer component for the PSA-style card grading application.
"""

import streamlit as st


def show_disclaimer():
    """Display the application disclaimer."""
    st.sidebar.markdown("---")
    with st.sidebar.expander("⚠️ Important Disclaimer", expanded=False):
        st.markdown("""
        **This application is for hobby and educational use only.**
        
        - **NOT affiliated** with PSA (Professional Sports Authenticator) or any official grading service
        - All grades are **estimates only** and should not be used for commercial decisions
        - Results may vary based on image quality, lighting, and card characteristics
        - This tool cannot replace professional grading services
        - Use at your own discretion for entertainment purposes
        
        **By using this application, you acknowledge that all results are unofficial estimates.**
        """)


def show_main_disclaimer():
    """Display disclaimer in main area when first loading."""
    st.error("""
    🚨 **IMPORTANT DISCLAIMER**
    
    This is an **unofficial hobby tool** for entertainment and educational purposes only. 
    It is **NOT affiliated with PSA** or any official grading service. 
    All grades are estimates and should not be used for commercial decisions.
    """)
    
    st.info("""
    📋 **What this tool does:**
    - Analyzes card images for centering, edges, corners, and surface condition
    - Provides transparent scoring with visual justification
    - Generates PSA-style grade estimates with detailed breakdowns
    - Offers configurable rubrics and batch processing capabilities
    """)


def get_disclaimer_text() -> str:
    """Return disclaimer text for reports and exports."""
    return """
DISCLAIMER: This analysis was generated by an unofficial hobby tool for entertainment 
and educational purposes only. It is NOT affiliated with PSA (Professional Sports 
Authenticator) or any official grading service. All grades are estimates only and 
should not be used for commercial decisions. Professional grading services should 
be consulted for official evaluations.
"""